'use client';

export default function Privacy() {
  return (
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 mb-4">
        Privacy Policy
      </h1>
      <p className="text-gray-600 mb-8">Updated at 2025-01-26</p>

      <div className="prose prose-lg max-w-none">
        <p className="text-gray-600 mb-8">
          NoCodeGuy ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy
          explains how your personal information is collected, used, and disclosed by
          NoCodeGuy.
        </p>
        <p className="text-gray-600 mb-8">
          This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our
          application, NoCodeGuy. By accessing or using our Service, you signify that you have read, understood, and agree to
          our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our
          Terms of Service.
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Definitions and key terms</h2>
          <p className="text-gray-600 mb-4">
            To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced,
            are strictly defined as:
          </p>
          <ul className="list-disc list-inside text-gray-600 space-y-2">
            <li>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your
              browser, provide analytics, remember information about you such as your language preference or login information.
            </li>
            <li>Company: when this policy mentions "Company," "we," "us," or "our," it refers to
              NoCodeGuy, that is responsible for your information under this Privacy Policy.
            </li>
            <li>Country: where NoCodeGuy or the owners/founders of NoCodeGuy are based, in this case is Germany</li>
            <li>Customer: refers to the company, organization or person that signs up to use the
              NoCodeGuy Service to manage the relationships with your consumers or service users.
            </li>
            <li>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to
              visit NoCodeGuy and use the services.
            </li>
            <li>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP)
              address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the
              location from which a device is connecting to the Internet.
            </li>
            <li>Personnel: refers to those individuals who are employed by NoCodeGuy or are under contract to perform a service
              on behalf of one of the parties.
            </li>
            <li>Personal Data: any information that directly, indirectly, or in connection with other information — including a
              personal identification number — allows for the identification or identifiability of a natural person.
            </li>
            <li>Service: refers to the service provided by NoCodeGuy as described in the relative terms (if available) and on this platform.</li>
            <li>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who
              provide our content or whose products or services we think may interest you.
            </li>
            <li>Website: NoCodeGuy's site, which can be accessed via this URL: nocodeguy.dev</li>
            <li>You: a person or entity that is registered with NoCodeGuy to use the Services.</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">What Information Do We Collect?</h2>
          <p className="text-gray-600 mb-4">
            We collect information from you when you visit our website, register on our site, place an order, subscribe to our
            newsletter, respond to a survey or fill out a form.
          </p>
          <ul className="list-disc list-inside text-gray-600 mb-4">
            <li>Email Addresses</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Use The Information We Collect?</h2>
          <p className="text-gray-600 mb-4">
            Any of the information we collect from you may be used in one of the following ways:
          </p>
          <ul className="list-disc list-inside text-gray-600 space-y-2">
            <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
            <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>
            <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
            <li>To process transactions</li>
            <li>To administer a contest, promotion, survey or other site feature</li>
            <li>To send periodic emails</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">When does NoCodeGuy use end user information from third parties?</h2>
          <p className="text-gray-600 mb-4">
            NoCodeGuy will collect End User Data necessary to provide the NoCodeGuy services to our customers.
          </p>
          <p className="text-gray-600 mb-4">
            End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">When does NoCodeGuy use customer information from third parties?</h2>
          <p className="text-gray-600 mb-4">
            We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a NoCodeGuy customer, we receive information from a third party that provides automated fraud detection services to NoCodeGuy. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Do we share the information we collect with third parties?</h2>
          <p className="text-gray-600 mb-4">
            We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
          </p>
          <p className="text-gray-600 mb-4">
            We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
          </p>
          <p className="text-gray-600 mb-4">
            We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and type of the device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers.
          </p>
          <p className="text-gray-600 mb-4">
            We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Where and when is information collected from customers and end users?</h2>
          <p className="text-gray-600 mb-4">
            NoCodeGuy will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Use Your Email Address?</h2>
          <p className="text-gray-600 mb-4">
            By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do.
          </p>
          <p className="text-gray-600 mb-4">
            By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy.
          </p>
          <p className="text-gray-600 mb-4">
            Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Long Do We Keep Your Information?</h2>
          <p className="text-gray-600 mb-4">
            We keep your information only so long as we need it to provide NoCodeGuy to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we'll either remove it from our systems or depersonalize it so that we can't identify you.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">How Do We Protect Your Information?</h2>
          <p className="text-gray-600 mb-4">
            We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to NoCodeGuy or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Information about General Data Protection Regulation (GDPR)</h2>
          <p className="text-gray-600 mb-4">
            We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">California Online Privacy Protection Act (CalOPPA)</h2>
          <p className="text-gray-600 mb-4">
            CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Kids' Privacy</h2>
          <p className="text-gray-600 mb-4">
            We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Changes To Our Privacy Policy</h2>
          <p className="text-gray-600 mb-4">
            We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">Contact Information</h2>
          <p className="text-gray-600 mb-4">
            If you have any questions about this Privacy Policy, please contact us by sending an email to hi@nocodeguy.dev
          </p>
        </section>
      </div>
    </main>
  );
}
